### PR TITLE
Support uploading to Project and Screen objects

### PR DESCRIPTION
**Pull request by DavidStirling**
Expands upload support to cover Projects and Screens

### CODE REVIEW

**Comment by sbesson** [comment]
As we are widening the scope of the objects to which tables can be linked, would it make sense to provisionally add ROI ?

**Comment by DavidStirling** [comment]
Is it possible to find ROI-linked tables in OMERO.web? I figured for ROI support the approach would be to associate the table with a parent image and have a separate ROI link added to it.

**Comment by sbesson** [comment]
> Is it possible to find ROI-linked tables in OMERO.web?

Not currently. No objections to draw the line as "anything that gets created/updated/read via `omero2pandas` must be accessible and manageable via OMERO.web webclient" at least for the time being

**Comment by emilroz** [comment]
@sbesson do you have any specific workflows in mind? I think the ROI_Converter_NGFF is linking ROI-type tables to Images. But let us know if there's something specific we should take into account here.

**Comment by sbesson** [comment]
I don't have any specific workflow in mind but I was generally thinking  tabular data associated to label images. At the moment, the existing tooling links these tables at the Image level but there are ongoing discussions about linking them at the ROI level. This will in turn raise all the management questions via the UI brought by @DavidStirling.

I suggest we do not block this PR on this discussion. Project/Screen tabular annotations are well-established workflows and there is no reason `omero2pandas` should not be able to handle those.

**Review by sbesson — APPROVED** [review]
Successfully tested the `upload_table` workflow using both a `Project` and a `Screen` target

**Pull request merged**
